### ISSUE TITLE
Request: Access to v0.2.0-alpha1

### ISSUE THREAD

**Issue by opooladz** [haowen-xu/tfsnippet#45]
Thank you for this repo. 

This [repo's](https://github.com/NetManAIOps/OmniAnomaly/blob/master/requirements.txt) requirements.txt makes use use of the v0.2.0-alpha1 version of your tfsnippet repo. Is it possible to put this version back up please? 

Thanks in advance.

**Comment by jayantchen96** [comment]
> Thank you for this repo.
> 
> This [repo's](https://github.com/NetManAIOps/OmniAnomaly/blob/master/requirements.txt) requirements.txt makes use use of the v0.2.0-alpha1 version of your tfsnippet repo. Is it possible to put this version back up please?
> 
> Thanks in advance.

Hi, you can find it in this link https://github.com/haowen-xu/tfsnippet/releases
